### ISSUE TITLE
Additional getInfo Data

### ISSUE THREAD

**Issue by GrimnebulinAhab** [tirnovar/Power_BI_REST_API_PQ#1]
First, thank you for putting this connector together! It is very useful. Is it possible to get it updated to include all information? For example, when I run it locally, I get dataset and dataflow refresh schedules. Is it possible to add the necessary parameters to the call?

**Comment by tirnovar** [comment]
Hey, lots of this information are covered in ScanerAPI or inside AcitivityEvents.
